### PR TITLE
Linux as bootloader

### LINKED ISSUE #75: Flaky bootup on initial boot
I've seen this live but now also in the integration tests (which is excellent).
The full bootlog looks like this:
```
qemu-system-arm: Aspeed iBT has no chardev backend

DRAM Init-DDR3
CBR0-1357135713571357
CBR134Done


U-Boot 2016.07-00038-gc7a5629a1c (Oct 02 2018 - 21:27:29 +0000)

DRAM:  240 MiB
WARNING: Caches not enabled
Flash: 32 MiB
Using default environment

In:    serial
Out:   serial
Err:   serial
Net:   aspeednic#0
Error: aspeednic#0 address not set.

Hit any key to stop autoboot:  0 
ubi0: attaching mtd1
ubi0: scanning is finished

. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
|
. done
```

Then nothing. The CPU hangs.

The easiest thing here is probably figuring out why u-boot wants to "fix" the filesystem in the first place, that would significantly speed up the initial boot after installation as well.

### LINKED ISSUE #112: Remove u-boot and use Linux as bootloader
Seeing as we don't need u-boot, and the philosophy we try to follow is the lesser amount of attack surfaces - having Linux as the bootloader makes sense.

This would make #6 (possibly, it would make it easier to solve anyhow), #75, #76 obsolete and would allow us to insert early boot code (like LPC disable) on platforms to make the whole system function better.

### PR DESCRIPTION
**Pull request by bluecmd**
a.k.a LinuxBoot for BMC

Fixes #112, closes #75, #76 as obsolete

What's left?
1. Verify cold and warm boot on physical hardware

Future work in follow-up PRs:
1. Embed kernel checksum in DTB to prevent mix&match attacks
2. Move UART default baud rate to board Makefile.inc, allow easy user override

### CODE REVIEW

File: boot/loader/main.go [hunk 1]
```diff
@@ -70,9 +66,35 @@ func main() {
...
 	}
 	log.Printf("Integrity check OK")
-	err = unix.Exec("/init", []string{"/init"}, os.Environ())
-	// This is only reached if Exec somehow failed
-	log.Fatalf("exec: %v", err)
+
+	// Load the real kernel
+	// TODO(bluecmd): Use u-root kexec package when it supports ARM
+	// https://github.com/u-root/u-root/issues/401
+	unix.Mknod("/dev/null", unix.S_IFCHR|0600, 0x0103)
```
Comment (golangcibot) [inline boot/loader/main.go]: Error return value of `unix.Mknod` is not checked

File: boot/loader/main.go [hunk 2]
```diff
@@ -70,9 +66,35 @@ func main() {
...
+	unix.Mkdir("/proc", 0755)
```
Comment (golangcibot) [inline boot/loader/main.go]: Error return value of `unix.Mkdir` is not checked

File: boot/loader/main.go [hunk 3]
```diff
@@ -70,9 +66,35 @@ func main() {
...
+	unix.Mkdir("/sys", 0755)
```
Comment (golangcibot) [inline boot/loader/main.go]: Error return value of `unix.Mkdir` is not checked

**Comment by bluecmd** [comment]
This is a huge patch as it pulls in a lot of changes in one go and I didn't see any meaningful ways of splitting this up as they are all intertwined in how the flash layout is calculated.

- Previously only one Linux kernel was built, now a `boot` and a `full` kernel is built.
  - There is a `make linux-menuconfig-*` target that allows changing the config for either one easily
- U-boot is gone and required moving very SoC specific firmware, which required some moves around that I planned to do anyway
  - `platform/$PLATFORM/Makefile.inc` configures board specific parameters like which SoC is used (like ast2400)
  - `platform/$SOC/boot/` contains the bootloader for the SoC.
  - `platform/$PLATFORM/platform.dts` is the device tree for both the boot kernel and the full kernel with `#if(n)def BOOTLOADER` guards for things that is only specific for the bootloader/full.
  - `platform/$SOC/linux.config.{full,boot}` is the location for the kernel config in use
  - `platform/cmd/*` are tools that calculate the flash layout and data addresses
- u-root's kexec does not support ARM yet, so I'm downloading a home-built version to avoid having the user compile it (would require a full libc toolchain).

**Comment by bluecmd** [comment]
Cold boot verified
